_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-x86_64
batch_size:
    value: 16
learning_rate:
    value: 0.0001
